# Generated by Django 3.1.7 on 2021-05-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='L1',
            new_name='L',
        ),
    ]
