# Generated by Django 3.1.7 on 2021-05-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0002_auto_20210530_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='impulse',
            new_name='pulse',
        ),
    ]
