# Generated by Django 3.1.7 on 2021-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_auto_20210530_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='norm_length',
            field=models.CharField(choices=[('L_cp', 'L_cp'), ('L_D2', 'L_D2'), ('L_D3', 'L_D3'), ('L_NL', 'L_NL'), ('L_S', 'L_S'), ('L_ICS', 'L_ICS')], default='L_cp', max_length=5, verbose_name='Нормирующая длина'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='pulse',
            field=models.CharField(choices=[('Гауссовский импульс', 'Гауссовский импульс'), ('Супергауссовский импульс', 'Супергауссовский импульс'), ('Солитоноподобный импульс', 'Солитоноподобный импульс')], max_length=24, verbose_name='Форма импульса'),
        ),
    ]
